# Generated by Django 4.1.7 on 2023-02-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='отчество')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='фамилия')),
                ('director_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
        ),
    ]
