# Generated by Django 4.1.7 on 2023-02-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_dressingroom_alter_actor_gender_actor_dressing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressingroom',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dressingroom',
            name='number',
            field=models.IntegerField(),
        ),
    ]
