# Generated by Django 4.1.7 on 2023-02-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_alter_dressingroom_floor_alter_dressingroom_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressingroom',
            name='floor',
            field=models.IntegerField(verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='dressingroom',
            name='number',
            field=models.IntegerField(verbose_name='кабинет'),
        ),
    ]
